
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: sh -c "sleep 10 && python -m src.dashboard_visualizer.dashboard_flask"
    ports:
      - "5001:5001"
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://admin:admin123@db:5432/flaskdb
      - MODE=docker

  webhook:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python src/webhook_receptor/webhook_flask.py
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://admin:admin123@db:5432/flaskdb

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:

